Repository osunyorg/theme, pull requests merged in 2024-11, with the labels that each got.

#705 Mise à niveau du bloc contact
  assets/sass/_theme/blocks/contact.sass
  assets/sass/_theme/blocks/organizations.sass
  assets/sass/_theme/design-system/footer.sass
  assets/sass/_theme/design-system/transcription.sass
  assets/sass/_theme/design-system/typography.sass
  assets/sass/_theme/sections/locations.sass
  layouts/partials/blocks/templates/contact.html
  layouts/partials/blocks/templates/organizations/map.html
  layouts/partials/commons/address.html
  layouts/partials/commons/contact-details.html
  layouts/partials/footer/site.html
  layouts/partials/header/hero.html
  layouts/partials/locations/hero-address.html
  layouts/partials/locations/hero-single.html
  layouts/partials/locations/location.html
Labels: need admin

#727 Retrait du `role="figure"` des figures sans contenu textuel (crédit, alt ou texte)
  layouts/partials/blocks/templates/call_to_action.html
  layouts/partials/blocks/templates/features.html
  layouts/partials/blocks/templates/testimonials/single.html
  layouts/partials/organizations/logo.html
  layouts/partials/programs/image.html
Labels: adjustment, a11y

#728 Search : fix de la fermeture avec le bouton et de l'overlay
  assets/js/theme/design-system/search.js
  assets/sass/_theme/design-system/header.sass
Labels: bug

#715 Ajout des "signatures" des auteurs et autrices à la suite du contenu d'un article
  assets/sass/_theme/sections/posts.sass
  assets/sass/_theme/utils/sidebar.sass
  config.yaml
  i18n/fr.yml
  layouts/partials/posts/post-infos.html
  layouts/partials/posts/signature.html
  layouts/posts/single.html
Labels: enhancement, Incidence faible 😌

#736 Visionneuse ajustements d'accessibilité
  assets/js/theme/design-system/extendables.js
  assets/sass/_theme/components/lightbox.sass
  i18n/en.yml
  i18n/fr.yml
  i18n/pt.yml
  layouts/partials/commons/lightbox/lightbox.html
Labels: a11y

#737 Ajout des traductions pour les signatures
  i18n/en.yml
  i18n/pt.yml
  layouts/partials/posts/signature.html
Labels: adjustment

#735 [A11Y] Amélioration de l'accessibilité des blocs en carte
  assets/sass/_theme/dependencies/leaflet.sass
  layouts/partials/blocks/templates/organizations/map.html
Labels: adjustment, a11y

#738 Masquer les signatures lorsqu'elles n'ont pas d'auteur ou autrice
  layouts/posts/single.html
Labels: adjustment

#739 Faire chasser les longs liens dans les publications
  assets/sass/_theme/sections/publications.sass
Labels: bug, adjustment

#795 Ajout d'une config pour désactiver les lightbox dans les blocs de galerie
  hugo.yaml
  layouts/partials/blocks/templates/gallery.html
  layouts/partials/commons/image-figure.html
Labels: adjustment, a11y
