Repository osunyorg/theme, pull requests merged in 2024-07, with the labels that each got.

#491 Ajustement de la taille du bouton de partage d'une formation lorsqu'il est seul
  assets/sass/_theme/sections/diplomas.sass
Labels: Incidence faible 😌, adjustment

#494 Ajout de l'email et du flux rss aux liens sociaux
  i18n/es.yml
  layouts/partials/commons/socials.html
Labels: Incidence faible 😌, adjustment

#493 Alignement et standardisation des options des blocs
  assets/sass/_theme/blocks/posts.sass
  assets/sass/_theme/sections/posts.sass
  config.yaml
  layouts/partials/blocks/templates/agenda.html
  layouts/partials/blocks/templates/organizations.html
  layouts/partials/blocks/templates/pages.html
  layouts/partials/blocks/templates/pages/alternate.html
  layouts/partials/blocks/templates/pages/cards.html
  layouts/partials/blocks/templates/pages/grid.html
  layouts/partials/blocks/templates/pages/large.html
  layouts/partials/blocks/templates/pages/list.html
  layouts/partials/blocks/templates/persons.html
  layouts/partials/blocks/templates/posts.html
  layouts/partials/blocks/templates/posts/alternate.html
  layouts/partials/blocks/templates/posts/highlight.html
  layouts/partials/blocks/templates/posts/large.html
  layouts/partials/contents/backlinks.html
  layouts/partials/events/event.html
  layouts/partials/events/events.html
  layouts/partials/pages/children.html
  layouts/partials/persons/person.html
  layouts/partials/persons/posts.html
  layouts/partials/posts/post.html
  layouts/partials/posts/posts.html
Labels: Incidence moyenne 😲, adjustment, Rangement

#502 Bloc call to action : layout "discret"
  assets/sass/_theme/blocks/call_to_action.sass
  assets/sass/_theme/configuration/blocks.sass
  layouts/partials/blocks/templates/call_to_action.html
Labels: feature, Incidence faible 😌

#500 Accessibilité des blocs
  assets/sass/_theme/blocks/pages.sass
  config.yaml
  i18n/en.yml
  i18n/fr.yml
  layouts/partials/blocks/templates/links.html
  layouts/partials/blocks/templates/pages/alternate.html
  layouts/partials/blocks/templates/posts/highlight.html
  layouts/partials/blocks/templates/posts/large.html
  layouts/partials/blocks/templates/projects/large.html
  layouts/partials/commons/categories.html
  layouts/partials/events/categories.html
  layouts/partials/events/event-infos.html
  layouts/partials/posts/categories.html
  layouts/partials/posts/post-infos.html
  layouts/partials/posts/post.html
  layouts/partials/projects/categories.html
  layouts/partials/projects/project-infos.html
  layouts/partials/projects/project.html
Labels: Incidence moyenne 😲, adjustment, Rangement

#510 Problème d'affichage des icônes dans le bloc papiers
  assets/sass/_theme/blocks/files.sass
  assets/sass/_theme/blocks/gallery.sass
  assets/sass/_theme/design-system/button.sass
  assets/sass/_theme/sections/papers.sass
  assets/sass/_theme/utils/icons.sass
  layouts/partials/papers/actions.html
Labels: bug, Incidence faible 😌

#519 Correction de l'affichage des icônes dans le bloc contact et dans le footer
  assets/sass/_theme/blocks/contact.sass
  assets/sass/_theme/design-system/footer.sass
Labels: Incidence faible 😌, adjustment

#518 Correction du soulignement des liens dans le header
  assets/sass/_theme/design-system/nav.sass
Labels: Incidence faible 😌, adjustment

#521 Ajout de la couleur de header aux liens du menu
  assets/sass/_theme/design-system/nav.sass
Labels: Incidence faible 😌, adjustment

#524 Correction de la couleur des boutons de splide
  assets/sass/_theme/dependencies/splide.sass
Labels: bug, Incidence faible 😌

#525 Actualités mises en avant : problème d'options
  assets/sass/_theme/blocks/posts.sass
  layouts/partials/blocks/templates/posts/highlight.html
Labels: bug, Incidence moyenne 😲

#527 Ajustement de la variable de couleur pour les liens des dropdowns du menu
  assets/sass/_theme/design-system/nav.sass
Labels: Incidence faible 😌, adjustment

#513 Ajout de nouvelles options aux blocs
  assets/js/theme/blocks/organizations.js
  assets/sass/_theme/blocks/organizations.sass
  assets/sass/_theme/blocks/posts.sass
  assets/sass/_theme/blocks/programs.sass
  assets/sass/_theme/sections/events.sass
  assets/sass/_theme/sections/locations.sass
  assets/sass/_theme/sections/organizations.sass
  assets/sass/_theme/sections/persons.sass
  assets/sass/_theme/sections/posts.sass
  assets/sass/_theme/utils/icons.sass
  assets/sass/_theme/utils/shame.sass
  config.yaml
  layouts/partials/GetTruncateContent
  layouts/partials/blocks/templates/locations.html
  layouts/partials/blocks/templates/organizations.html
  layouts/partials/blocks/templates/organizations/grid.html
  layouts/partials/blocks/templates/organizations/map.html
  layouts/partials/blocks/templates/persons.html
  layouts/partials/blocks/templates/posts/highlight.html
  layouts/partials/blocks/templates/posts/large.html
  layouts/partials/blocks/templates/programs.html
  layouts/partials/events/event.html
  layouts/partials/locations/location.html
  layouts/partials/locations/locations.html
  layouts/partials/organizations/organization.html
  layouts/partials/organizations/organizations.html
  layouts/partials/persons/list-item.html
  layouts/partials/persons/list.html
  layouts/partials/persons/person.html
  layouts/partials/persons/persons-specific.html
  layouts/partials/posts/post.html
  layouts/partials/posts/posts.html
Labels: feature, Incidence faible 😌

#523 Léger fix : affichage des image des fonctionnalités
  assets/sass/_theme/blocks/features.sass
Labels: Incidence faible 😌, adjustment
