Repository osunyorg/theme, pull requests merged in 2024-08, with the labels that each got.

#536 Gestions des couleurs de fonds des dropdown sur mobile
  assets/sass/_theme/design-system/header.sass
  assets/sass/_theme/design-system/nav.sass
Labels: adjustment

#558 Ajout de l'image et du sous-titre aux options actives des événements
  config.yaml
Labels: Incidence faible 😌, adjustment

#559 Ajout d'une vérification dans le partial GetBlockClass
  layouts/partials/GetBlockClass
Labels: bug, Incidence faible 😌

#560 [A11Y] Retrait des balises vides dans les blocs
  layouts/partials/blocks/templates/links.html
  layouts/partials/persons/person.html
Labels: Incidence faible 😌, adjustment, a11y

#499 Es5 slider
  assets/js/theme/blocks/draggableBlocks.js
  assets/js/theme/blocks/timeline.js
  assets/js/theme/components/carousel.js
  assets/js/theme/components/carousel/arrows.js
  assets/js/theme/components/carousel/autoplayer.js
  assets/js/theme/components/carousel/carousel.js
  assets/js/theme/components/carousel/classes.js
  assets/js/theme/components/carousel/config.js
  assets/js/theme/components/carousel/events.js
  assets/js/theme/components/carousel/manager.js
  assets/js/theme/components/carousel/pagination.js
  assets/js/theme/components/carousel/paginationButton.js
  assets/js/theme/components/carousel/slide.js
  assets/js/theme/components/carousel/slider.js
  assets/js/theme/components/carousel/utils.js
  assets/js/theme/index.js
  assets/js/theme/utils/utils.js
  assets/sass/_theme/blocks/gallery.sass
  assets/sass/_theme/blocks/posts.sass
  assets/sass/_theme/blocks/testimonials.sass
  assets/sass/_theme/blocks/timeline.sass
  assets/sass/_theme/components/carousel.sass
  assets/sass/_theme/dependencies/splide.sass
  assets/sass/_theme/hugo-osuny.sass
  config.yaml
  i18n/en.yml
  i18n/fr.yml
  layouts/partials/blocks/templates/carousel.html
  layouts/partials/blocks/templates/gallery.html
  layouts/partials/blocks/templates/gallery/carousel-image.html
  layouts/partials/blocks/templates/gallery/carousel.html
  layouts/partials/blocks/templates/posts/carousel.html
  layouts/partials/blocks/templates/testimonials.html
  layouts/partials/blocks/templates/testimonials/single.html
  layouts/partials/blocks/templates/timeline.html
  layouts/partials/blocks/templates/timeline/horizontal.html
  layouts/partials/blocks/templates/timeline/vertical.html
  layouts/partials/footer/js.html
  layouts/partials/posts/post.html
Labels: enhancement, Incidence forte 😱, a11y

#573 Gestion elements informatifs css
  assets/sass/_theme/_utils.sass
  assets/sass/_theme/utils/a11y.sass
  layouts/partials/blocks/templates/carousel.html
Labels: a11y

#581 [A11Y] Ajout d'un label visible pour le TA et sans css aux liens externes
  layouts/partials/blocks/templates/links.html
  layouts/partials/blocks/templates/organizations.html
  layouts/partials/commons/share.html
  layouts/partials/locations/map.html
  layouts/partials/organizations/contact-details.html
  layouts/partials/persons/contact-details.html
  layouts/partials/persons/contacts.html
  layouts/partials/publications/downloads.html
Labels: Incidence faible 😌, adjustment, a11y

#580 Ajout d'élements textes SR dans les déclencheurs de lightbox
  layouts/partials/blocks/templates/chapter.html
  layouts/partials/blocks/templates/gallery/carousel-image.html
  layouts/partials/blocks/templates/gallery/grid.html
  layouts/partials/blocks/templates/gallery/large.html
  layouts/partials/blocks/templates/image.html
  layouts/partials/header/hero.html
Labels: a11y

#587 Gallerie carousel: Ajustement des hauteurs d'image
  assets/sass/_theme/blocks/gallery.sass
  assets/sass/_theme/configuration/blocks.sass
Labels: adjustment

#591 Couleurs des dropdowns du menu
  assets/sass/_theme/configuration/components.sass
  assets/sass/_theme/design-system/header.sass
Labels: Incidence faible 😌, adjustment

#590 Block organisations layout carte : largeur de la carte
  assets/sass/_theme/sections/organizations.sass
Labels: bug, Incidence faible 😌
