Repository osunyorg/theme, pull requests merged in 2024-06, with the labels that each got.

#448 Taille du bouton de partage dans les programmes
  assets/sass/_theme/sections/diplomas.sass
Labels: Incidence faible 😌, adjustment

#450 Fix de la taille du bouton de partage d'une formation pour tous les écrans
  assets/sass/_theme/sections/diplomas.sass
Labels: Incidence faible 😌, adjustment

#456 Configuration de l'index des posts
  config.yaml
Labels: Incidence faible 😌, adjustment

#458 Search en darkmode
  assets/sass/_theme/design-system/form.sass
  assets/sass/_theme/design-system/search.sass
Labels: Incidence faible 😌, adjustment

#411 Layout liste de l'index des projets
  assets/sass/_theme/blocks/projects.sass
  assets/sass/_theme/sections/projects.sass
  config.yaml
Labels: feature, Incidence moyenne 😲

#454 Ajout de variables au CTA / bouton pour styliser les bordures
  assets/sass/_theme/_variables.sass
  assets/sass/_theme/blocks/call_to_action.sass
  assets/sass/_theme/configuration/blocks.sass
  assets/sass/_theme/configuration/components.sass
  assets/sass/_theme/design-system/button.sass
Labels: feature, Incidence faible 😌

#459 Block liste des volumes
  assets/sass/_theme/blocks/volumes.sass
  assets/sass/_theme/hugo-osuny.sass
  layouts/partials/blocks/templates/volumes.html
  layouts/partials/volumes/volume.html
  layouts/partials/volumes/volumes.html
Labels: feature, Incidence faible 😌

#451 Gérer les animations des blocs chiffres clés avec la config
  assets/js/theme/blocks/keyFigures.js
  config.yaml
  layouts/partials/blocks/templates/key_figures.html
Labels: feature, Incidence faible 😌

#466 Gestion du nouveau répertoire du thème sur les sites
  .github/workflows/test-with-example.yml
  layouts/partials/head/css.html
  package.json
  theme.yaml
Labels: Incidence forte 😱, adjustment

#467 Ajout des réseaux sociaux au bloc Contact
  assets/sass/_theme/blocks/contact.sass
  i18n/en.yml
  i18n/fr.yml
  layouts/partials/blocks/templates/contact.html
  layouts/partials/commons/socials.html
  layouts/partials/footer/social.html
Labels: feature, Incidence faible 😌, adjustment

#468 Bug d'affichage du toc en mobile (ellipsis du texte)
  assets/sass/_theme/design-system/button.sass
Labels: bug, Incidence faible 😌

#464 Erreur de js dans les sites où on a enlevé le menu
  assets/js/theme/design-system/mainMenu.js
Labels: bug, Incidence faible 😌

#471 Ajustement de l'affichage des dates des événements en mobile
  assets/sass/_theme/sections/events.sass
  layouts/partials/events/event.html
Labels: Incidence faible 😌, adjustment

#474 Gestion de la taille des icônes png dans les blocs key_figures et features
  assets/sass/_theme/blocks/features.sass
  assets/sass/_theme/blocks/key_figures.sass
  assets/sass/_theme/configuration/blocks.sass
  layouts/partials/blocks/templates/key_figures.html
  layouts/partials/commons/image.html
Labels: Incidence moyenne 😲, adjustment
