Repository osunyorg/theme, pull requests merged in 2024-05, with the labels that each got.

#406 Nettoyage de la documentation
  docs/icons/Osuny.json
  docs/icons/readme.md
  docs/icons/selection.json
  docs/icons/svg/arrow-first.svg
  docs/icons/svg/arrow-last.svg
  docs/icons/svg/arrow-left.svg
  docs/icons/svg/arrow-right.svg
  docs/icons/svg/arrow.svg
  docs/icons/svg/burger.svg
  docs/icons/svg/caret-bottom.svg
  docs/icons/svg/caret-left.svg
  docs/icons/svg/caret-right.svg
  docs/icons/svg/caret-top.svg
  docs/icons/svg/caret.svg
  docs/icons/svg/close.svg
  docs/icons/svg/download.svg
  docs/icons/svg/eye.svg
  docs/icons/svg/facebook.svg
  docs/icons/svg/instagram.svg
  docs/icons/svg/link-blank.svg
  docs/icons/svg/linkedin.svg
  docs/icons/svg/list-hyphen.svg
  docs/icons/svg/pause.svg
  docs/icons/svg/play.svg
  docs/icons/svg/search.svg
  docs/icons/svg/social.svg
  docs/icons/svg/toc.svg
  docs/icons/svg/twitter.svg
Labels: Incidence faible 😌

#408 Problème d'affichage du statut des événements
  assets/sass/_theme/sections/events.sass
Labels: bug, Incidence faible 😌

#391 Refonte du bloc contact
  assets/sass/_theme/blocks/contact.sass
  i18n/en.yml
  i18n/fr.yml
  layouts/partials/blocks/templates/contact.html
Labels: Incidence moyenne 😲

#396 Timing des animation des modales
  assets/js/theme/design-system/mainMenu.js
  assets/js/theme/design-system/modal.js
  assets/sass/_theme/design-system/layout.sass
Labels: bug, Incidence faible 😌

#402 Location section layout
  assets/js/theme/blocks/campus.js
  assets/js/theme/index.js
  assets/sass/_theme/design-system/layout.sass
  assets/sass/_theme/sections/diplomas.sass
  assets/sass/_theme/sections/locations.sass
  config.yaml
  layouts/locations/term.html
  layouts/partials/footer/js.html
  layouts/partials/locations/diplomas.html
  layouts/partials/locations/map.html
  layouts/partials/locations/template-program.html
Labels: enhancement

#414 Réparation du lien en haut du bloc événements
  layouts/partials/blocks/templates/agenda.html
Labels: bug, Incidence faible 😌

#418 Links block
  assets/sass/_theme/blocks/links.sass
  assets/sass/_theme/configuration/blocks.sass
  assets/sass/_theme/hugo-osuny.sass
  config.yaml
  layouts/partials/blocks/templates/links.html
Labels: question, feature, Incidence faible 😌

#425 Problème d'affichage du bloc lien en format tablette
  assets/sass/_theme/blocks/links.sass
Labels: bug, Incidence faible 😌

#436 Affichage des metas des actualités en layout "large"
  assets/sass/_theme/blocks/posts.sass
Labels: Incidence moyenne 😲

#440 Stretched-link sur l'article entier dans le bloc campus
  assets/sass/_theme/blocks/programs.sass
Labels: Incidence faible 😌
