Repository osunyorg/theme, pull requests merged in 2025-05, with the labels that each got.

#1041 Bloc fichiers : ajout de l'image d'aperçu
  assets/sass/_theme/blocks/files.sass
  layouts/partials/blocks/templates/files.html
Labels: adjustment

#1039 Ajustement du formatage de la date d'un timeslot dans un événement
  layouts/partials/commons/agenda/dates.html
Labels: adjustment, a11y

#1049 Correction des appels de partials dans les campus
  layouts/partials/locations/single.html
  layouts/partials/locations/single/diplomas.html
Labels: bug

#1045 [a11y] Correction du `aria-hidden` sur les blocs de titre
  layouts/partials/blocks/templates/title.html
Labels: a11y, Conformité RGAA

#1044 Correction du titre de menu dropdown
  layouts/partials/commons/menu-dropdown.html
Labels: a11y, Conformité RGAA

#1046 Bloc personnes : correction du niveau de titre
  layouts/partials/blocks/templates/persons.html
Labels: a11y, Conformité RGAA

#1067 Correction de la nav vide dans le footer
  layouts/partials/footer/social.html
Labels: bug, a11y

#1071 Correctif du partial "site" du footer
  layouts/partials/footer/site.html
Labels: bug

#1075 Événement : ajout d'une traduction à l'anglais
  i18n/en.yml
Labels: bug

#1054 [a11y] Correction du bloc lien
  layouts/partials/blocks/templates/links.html
Labels: Discussion wanted 🤔
